---
- name: "enos: configure trunk port"
  enos_command:
    commands:
      - enable
      - configure terminal
      - "terminal dont-ask"
      - "interface port {{ ml2_port_name }}"
      - no switchport trunk allowed vlan
      - switchport mode trunk
      - switchport trunk allowed vlan [{{ ml2_segmentation_id }}{% for vlan in trunked_vlans %},{{ vlan }}{% endfor %}]"
      - "switchport trunk native vlan {{ ml2_segmentation_id }}"
  register: result
  connection: network_cli
