---
- name: "enos: create vlan"
  enos_command:
    commands:
      - enable
      - configure terminal
      - "vlan {{ ml2_segmentation_id }}"
      - "name {{ ml2_segmentation_name }}"
  register: result
  connection: network_cli
