---
- name: "enos: delete port"
  enos_command:
    commands:
      - enable
      - configure terminal
      - "terminal dont-ask"
      - "interface port {{ ml2_port_name }}"
      - no switchport trunk allowed vlan
      - switchport mode access
      - no switchport access vlan
  register: result
  connection: network_cli
